name: Build and Release Sorting CLI

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build binary (macOS amd64)
        run: |
          GOOS=darwin GOARCH=amd64 go build -o sorting main.go

      - name: Build binary (macOS arm64)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o sorting-arm64 main.go

      - name: Build binary (Linux amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o sorting-linux main.go

      - name: Build binary (Linux arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -o sorting-arm64 main.go

      - name: Build binary (Windows amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o sorting.exe main.go

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          files: |
            sorting-darwin
            sorting-darwin-arm64
            sorting-linux
            sorting-linux-arm64
            sorting.exe
